name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Environment Variables
        run: echo '${{ secrets.ENV_FILE }}' > .env

      - name: Setup Node
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 16.x

      - name: Install Dependencies
        run: npm ci

      - name: Lint Project
        run: npm run lint

      - name: Compile Project
        run: npm run compile

      - name: Deploy Website
        if: ${{ github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: public
